(function (ZcarezeApp){
  ZcarezeApp.config(["$sceProvider", "$httpProvider", "$logProvider", "$stateProvider", "$urlRouterProvider", function($sceProvider,$httpProvider,$logProvider,$stateProvider,$urlRouterProvider) {

    var ictionaryTables = {}, dictionaryTableName = [];

    $stateProvider
      .state('app.model-account',{
          views:{
              'modelView':{
                  templateUrl:"view/account/account.html",
                  controller:"AccountCtrl",
                  resolve:{
                      deps:ZcarezeApp.loadControllerJs('js/controllers/account/AccountCtrl.js')
                  }
              }
          }
      })
      .state('app.model-account-residentinfo',{
          views:{
              'modelView':{
                  templateUrl:"view/account/residentinfo.html",
                  controller:"ResidentinfoCtrl",
                  resolve:{
                      deps:ZcarezeApp.loadControllerJs('js/controllers/account/ResidentinfoCtrl.js')
                  }
              }
          }
      })
      
      .state('app.model-account-myaccountinfo',{
          views:{
              'modelView':{
                  templateUrl:"view/account/myaccountinfo.html",
                  controller:"MyaccountinfoCtrl",
                  resolve:{
                      deps:ZcarezeApp.loadControllerJs('js/controllers/account/MyaccountinfoCtrl.js')
                  }
              }
          }
      })
      .state('app.model-account-signing',{
          views:{
              'modelView':{
                  templateUrl:"view/account/signing.html",
                  controller:"SigningCtrl",
                  resolve:{
                      deps:ZcarezeApp.loadControllerJs('js/controllers/account/SigningCtrl.js')
                  }
              }
          }
      })
      .state('app.model-account-lifehabit',{
          views:{
              'modelView':{
                  templateUrl:"view/account/lifehabit.html",
                  controller:"LifehabitCtrl",
                  resolve:{
                      deps:ZcarezeApp.loadControllerJs('js/controllers/account/LifehabitCtrl.js')
                  }
              }
          }
      })
      .state('app.model-account-basic',{
          views:{
              'modelView':{
                  templateUrl:"view/account/basic.html",
                  controller:"BasicCtrl",
                  resolve:{
                      deps:ZcarezeApp.loadControllerJs('js/controllers/account/BasicCtrl.js')
                  }
              }
          }
      })
      .state('app.model-account-qrcode',{
          views:{
              'modelView':{
                  templateUrl:"view/account/qrcode.html",
                  controller:"QrcodeCtrl",
                  resolve:{
                      deps:ZcarezeApp.loadControllerJs('js/controllers/account/QrcodeCtrl.js')
                  }
              }
          }
      });
  }])
})(ZcarezeApp)